#!/bin/sh

cat <<EOF | xmenu "$@"  | sh &
Web Browsers
	IMG:/etc/p3ng0s/icons/chromium.png	Chromium	chromium --no-sandbox
Applications
	IMG:/etc/p3ng0s/icons/gimp.png	Image editor	gimp
	IMG:/etc/p3ng0s/icons/system-file-manager.png	File Manager	nautilus
	IMG:/etc/p3ng0s/icons/vlc.png	Vlc	vlc
	IMG:/etc/p3ng0s/icons/filezilla.png	FileZilla	filezilla
	IMG:/etc/p3ng0s/icons/transmission.png	Transmission	transmission-gtk
Pentesting
	IMG:/etc/p3ng0s/icons/BurpSuite.png	BurpSuite	BurpSuiteCommunity
	IMG:/etc/p3ng0s/icons/wireshark.png	Wireshark	 wireshark
Tools
	IMG:/etc/p3ng0s/icons/remmina.png	Remmina	remmina
	IMG:/etc/p3ng0s/icons/gparted.png	Gparted	kdesu gparted
	IMG:/etc/p3ng0s/icons/postman.png	Postman	postman
	IMG:/etc/p3ng0s/icons/gpick.png	Gpick	gpick
	IMG:/etc/p3ng0s/icons/sqlite.png	DB Browser	sqlitebrowser
Editors
	IMG:/etc/p3ng0s/icons/vim.png	Vim	st vim

IMG:/etc/p3ng0s/icons/terminal.png	Terminal (st)		st tmux

IMG:/etc/p3ng0s/icons/help.png	Help	dmenu_splain "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "${10}" '-h' '25' '-bw' 'p' '-l' '15' '-p' '$' '-b'
IMG:/etc/p3ng0s/icons/themes.png	Theme	lxappearance
IMG:/etc/p3ng0s/icons/sound.png	Sound	pavucontrol

IMG:/etc/p3ng0s/icons/edit-delete.png	Force Quit		xkill
IMG:/etc/p3ng0s/icons/system-shutdown.png	Shutdown		poweroff
IMG:/etc/p3ng0s/icons/view-refresh.png	Reboot			reboot
EOF
