#!/bin/sh

cat <<EOF | xmenu "$@"  | sh &
World Wide Web
	IMG:/etc/p3ng0s/icons/chromium.png	Chromium	chromium
	IMG:/etc/p3ng0s/icons/neo4j.png	Neo4j Database	chromium "http://127.0.0.1:7474/"
	IMG:/etc/p3ng0s/icons/wifipineapple.png	Wifi Pineapple	chromium "http://172.16.42.1:1471/"
	IMG:/etc/p3ng0s/icons/p3ng0s.png	p3ng0s Wiki	chromium "https://leosmith.wtf/rice/"
	IMG:/etc/p3ng0s/icons/havoc.png	Havoc wiki	chromium "https://havocframework.com/"
	IMG:/etc/p3ng0s/icons/suckless.png	Suckless	chromium "https://dwm.suckless.org"
	IMG:/etc/p3ng0s/icons/arch.png	Arch Wiki	chromium "https://wiki.archlinux.org/"
	IMG:/etc/p3ng0s/icons/notion.png	Notion	chromium "https://notion.so/"
	IMG:/etc/p3ng0s/icons/github.png	Github	chromium "https://github.com/"
	IMG:/etc/p3ng0s/icons/hackerone.png	HackerOne	chromium "https://hackerone.com/"
Networking
	IMG:/etc/p3ng0s/icons/wireshark.png	Wireshark	 wireshark
	IMG:/etc/p3ng0s/icons/filezilla.png	FileZilla	filezilla
	IMG:/etc/p3ng0s/icons/remmina.png	Remmina	remmina
System
	IMG:/etc/p3ng0s/icons/system-file-manager.png	File Manager	nautilus
	IMG:/etc/p3ng0s/icons/gimp.png	Image editor	gimp
	IMG:/etc/p3ng0s/icons/gparted.png	Gparted	kdesu gparted
	IMG:/etc/p3ng0s/icons/gpick.png	Gpick	gpick
Entertainment
	IMG:/etc/p3ng0s/icons/vlc.png	Vlc	vlc
	IMG:/etc/p3ng0s/icons/transmission.png	Transmission	transmission-gtk
Pentesting
	IMG:/etc/p3ng0s/icons/BurpSuite.png	BurpSuite	BurpSuitePro
	IMG:/etc/p3ng0s/icons/bloodhound.png	Bloodhound	Bloodhound
	IMG:/etc/p3ng0s/icons/havoc.png	Havoc	havocclient
Development
	IMG:/etc/p3ng0s/icons/vim.png	Vim	st vim
	IMG:/etc/p3ng0s/icons/sqlite.png	DB Browser	sqlitebrowser
	IMG:/etc/p3ng0s/icons/qflipper.png	qFlipper	kdesu qFlipper
	IMG:/etc/p3ng0s/icons/postman.png	Postman	postman
	IMG:/etc/p3ng0s/icons/virtman.png	Virtual Manager	kdesu virt-manager

IMG:/etc/p3ng0s/icons/terminal.png	Terminal (st)		st tmux

IMG:/etc/p3ng0s/icons/help.png	Help	dmenu_splain "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "${10}" '-h' '25' '-bw' 'p' '-l' '15' '-p' '$' '-b'
IMG:/etc/p3ng0s/icons/sound.png	Sound	pavucontrol

IMG:/etc/p3ng0s/icons/edit-delete.png	Force Quit		xkill
IMG:/etc/p3ng0s/icons/system-shutdown.png	Shutdown		poweroff
IMG:/etc/p3ng0s/icons/view-refresh.png	Reboot			reboot
EOF
